### ISSUE TITLE
TO-DO list

### ISSUE THREAD

**Issue by minimouse0** [231software/fullmoonplatform#1]
- [x] 设计第三方库格式规范
 - [ ] 插件间监听
 - [ ] build.ts
 - [ ] 权限系统（权限组）
 - [x] 加入**库优先级**，这个功能的意思是开发者可以选择插件引用的库来源优先级，比如说默认顺序为A库优先B库第二，那么编译的时候将会优先使用A中有的文件，如果A库中没有对应的文件才会选择B
 - [ ] 加入**指定库文件**，这个功能的意思是开发者可以手动指定某个文件必须来自于某个库，比如说指定了player.ts必须来源于example库，那么对于player.ts这个文件就会无视默认库优先级，直接采用example库中的这个文件  
 - [ ] 由于一些库的index.ts有依赖类型定义的情况，所以暂时采用了LNSDK的index.ts作为所有平台的index.ts，后续需要单独生成这个index.ts，来保证在没有LNSDK的情况下正常编译  
此任务是次要的，因为目前没有对LNSDK之外的库的刚需，LNSDK作为为满月平台验证可行性的第三方库（真的是第三方吗？），会尽全力实现所有满月平台规定的API  
文件移动逻辑：按照default中的顺序依次移动库，所有文件夹合并所有重名文件不替换，然后把满月平台的index.ts（满月平台的index.ts是绝对不能被第三方库自定义的）覆盖到用于编译的库中
 - [x] 在plugin.json中添加features项，features是满月平台提供的在各平台上实现非mc内置功能API的功能，配置文件中这是一个列表，可以写诸如ws，sqlite3这种，然后编译的时候满月平台会给支持这种npm包的平台直接在package.json中添加对应npm包，然后各库的实现方面会视平台情况，选择使用npm包或者引擎内置API
 - [x] 迁移平台特性配置至第三方库
 - [x] 加入常量，像插件名、插件目录这些
 - [x] 命令系统
 - [ ] 自定义维度系统（包含进游戏内置的三个维度）
 - [ ] 玩家类
 - [ ] 实体类
 - [x] 物品类
 - [x] 坐标类（FMPLocation）
 - [x] 玩家进服事件
 - [x] nodejs环境下通过readline模拟mc中的命令系统，其中只有插件提供的命令但没有mc服务器中的命令
 - [x] 解析yml的API
 - [ ] 解析xml的API
 - [x] 通过某种方案让fmp编译插件时把源码和库复制多份然后同时在不同的文件夹里同时开始编译各插件发行版
 - [x] 自定义表单和模式表单
 - [x] 多经济系统，依赖一些前置插件，他可以同时支持很多个经济插件，然后在服务器里寻找并使用，然后在根本没有任何经济前置的情况下会试图使用计分板经济
 - [x] SQL各种初阶操作函数
 - [ ] MySQL和SQL抽象层
 - [ ] 通过SQL实现的KVDB数据库

**Comment by minimouse0** [comment]
# 跟copilot聊了两句，给我做了一个简单的权限组，暂时还看不懂，希望开发到权限组的时候对大家有所启发
<details>

### 1. **设计权限系统架构**
确定你的权限系统的核心组件和如何相互交互。一般来说，你需要以下几个核心部分：
- **用户**：代表玩家或使用者。
- **权限节点**：权限的具体表示。
- **权限组**：将多个权限节点归类，方便管理。

### 2. **定义权限节点**
使用一个类或接口来表示权限节点，并为其分配唯一的字符串标识符。例如：
```typescript
class PermissionNode {
    constructor(public name: string, public description: string) {}
}

const flyPermission = new PermissionNode('fly', 'Allows the player to fly.');
```

### 3. **创建用户和权限组**
定义用户类，并为用户分配权限和权限组。你可以使用一个 Map 来管理用户和权限关系：
```typescript
class User {
    public permissions: Set<PermissionNode> = new Set();

    constructor(public name: string, public isAdmin: boolean = false) {}

    hasPermission(permission: PermissionNode): boolean {
        return this.permissions.has(permission) || this.isAdmin;
    }

    addPermission(permission: PermissionNode) {
        this.permissions.add(permission);
    }
}

class PermissionGroup {
    constructor(public name: string, public permissions: Set<PermissionNode> = new Set()) {}
    
    addPermission(permission: PermissionNode) {
        this.permissions.add(permission);
    }

    applyToUser(user: User) {
        this.permissions.forEach(permission => user.addPermission(permission));
    }
}
```

### 4. **管理权限**
实现权限管理的功能，如添加、删除权限节点，分配权限组等：
```typescript
class PermissionManager {
    public users: Map<string, User> = new Map();
    public groups: Map<string, PermissionGroup> = new Map();

    createUser(name: string, isAdmin: boolean = false): User {
        const user = new User(name, isAdmin);
        this.users.set(name, user);
        return user;
    }

    createGroup(name: string): PermissionGroup {
        const group = new PermissionGroup(name);
        this.groups.set(name, group);
        return group;
    }

    getUser(name: string): User | undefined {
        return this.users.get(name);
    }

    getGroup(name: string): PermissionGroup | undefined {
        return this.groups.get(name);
    }
}
```

### 5. **示例使用**
创建用户和权限组，分配权限并进行检查：
```typescript
const permissionManager = new PermissionManager();
const flyPermission = new PermissionNode('fly', 'Allows the player to fly.');
const adminGroup = permissionManager.createGroup('admin');
adminGroup.addPermission(flyPermission);

const user = permissionManager.createUser('Steve');
adminGroup.applyToUser(user);

console.log(user.hasPermission(flyPermission)); // true for admin group
```
当然！以下是根据示例代码整理的 TypeScript 权限组 API 的开发文档：

---

# 开发文档 - TypeScript 权限组 API

## 概述
本 API 提供了一套权限管理系统，允许为用户分配权限和权限组，并检查用户是否拥有特定权限。主要包含以下几个核心组件：
1. `PermissionNode` 权限节点类
2. `User` 用户类
3. `PermissionGroup` 权限组类
4. `PermissionManager` 权限管理类

---

## 类及方法详解

### 1. PermissionNode 类
**描述**：表示权限节点。

**属性**：
- `name: string` - 权限节点的名称。
- `description: string` - 权限节点的描述。

**构造函数**：
- `constructor(name: string, description: string)` - 创建一个新的权限节点。
    - `name`：权限节点的名称。
    - `description`：权限节点的描述。

```typescript
class PermissionNode {
    constructor(public name: string, public description: string) {}
}
```

---

### 2. User 类
**描述**：表示用户或玩家，并管理其权限。

**属性**：
- `name: string` - 用户名称。
- `isAdmin: boolean` - 是否为管理员。
- `permissions: Set<PermissionNode>` - 用户拥有的权限节点集合。

**构造函数**：
- `constructor(name: string, isAdmin: boolean = false)` - 创建一个新的用户。
    - `name`：用户名称。
    - `isAdmin`：是否为管理员，默认值为 `false`。

**方法**：
- `hasPermission(permission: PermissionNode): boolean` - 检查用户是否拥有特定权限。
    - `permission`：权限节点。
    - 返回值：`boolean` - 如果用户拥有该权限，则返回 `true`，否则返回 `false`。
- `addPermission(permission: PermissionNode)` - 为用户添加权限。
    - `permission`：权限节点。

```typescript
class User {
    public permissions: Set<PermissionNode> = new Set();

    constructor(public name: string, public isAdmin: boolean = false) {}

    hasPermission(permission: PermissionNode): boolean {
        return this.permissions.has(permission) || this.isAdmin;
    }

    addPermission(permission: PermissionNode) {
        this.permissions.add(permission);
    }
}
```

---

### 3. PermissionGroup 类
**描述**：表示权限组，可以将多个权限节点归类，方便管理。

**属性**：
- `name: string` - 权限组名称。
- `permissions: Set<PermissionNode>` - 权限组内的权限节点集合。

**构造函数**：
- `constructor(name: string, permissions: Set<PermissionNode> = new Set())` - 创建一个新的权限组。
    - `name`：权限组名称。
    - `permissions`：权限节点集合，默认值为空集合。

**方法**：
- `addPermission(permission: PermissionNode)` - 为权限组添加权限节点。
    - `permission`：权限节点。
- `applyToUser(user: User)` - 将权限组内的所有权限节点分配给用户。
    - `user`：用户。

```typescript
class PermissionGroup {
    constructor(public name: string, public permissions: Set<PermissionNode> = new Set()) {}
    
    addPermission(permission: PermissionNode) {
        this.permissions.add(permission);
    }

    applyToUser(user: User) {
        this.permissions.forEach(permission => user.addPermission(permission));
    }
}
```

---

### 4. PermissionManager 类
**描述**：管理用户和权限组的创建、删除及分配权限。

**属性**：
- `users: Map<string, User>` - 管理所有用户的 Map。
- `groups: Map<string, PermissionGroup>` - 管理所有权限组的 Map。

**构造函数**：无

**方法**：
- `createUser(name: string, isAdmin: boolean = false): User` - 创建一个新的用户并添加到用户列表中。
    - `name`：用户名称。
    - `isAdmin`：是否为管理员，默认值为 `false`。
    - 返回值：`User` - 创建的用户对象。
- `createGroup(name: string): PermissionGroup` - 创建一个新的权限组并添加到权限组列表中。
    - `name`：权限组名称。
    - 返回值：`PermissionGroup` - 创建的权限组对象。
- `getUser(name: string): User | undefined` - 获取指定名称的用户。
    - `name`：用户名称。
    - 返回值：`User | undefined` - 如果找到该用户，则返回用户对象；否则返回 `undefined`。
- `getGroup(name: string): PermissionGroup | undefined` - 获取指定名称的权限组。
    - `name`：权限组名称。
    - 返回值：`PermissionGroup | undefined` - 如果找到该权限组，则返回权限组对象；否则返回 `undefined`。

```typescript
class PermissionManager {
    public users: Map<string, User> = new Map();
    public groups: Map<string, PermissionGroup> = new Map();

    createUser(name: string, isAdmin: boolean = false): User {
        const user = new User(name, isAdmin);
        this.users.set(name, user);
        return user;
    }

    createGroup(name: string): PermissionGroup {
        const group = new PermissionGroup(name);
        this.groups.set(name, group);
        return group;
    }

    getUser(name: string): User | undefined {
        return this.users.get(name);
    }

    getGroup(name: string): PermissionGroup | undefined {
        return this.groups.get(name);
    }
}
```

---

## 示例代码
以下是如何使用该 API 的一个简单示例：

```typescript
const permissionManager = new PermissionManager();
const flyPermission = new PermissionNode('fly', 'Allows the player to fly.');
const adminGroup = permissionManager.createGroup('admin');
adminGroup.addPermission(flyPermission);

const user = permissionManager.createUser('Steve');
adminGroup.applyToUser(user);

console.log(user.hasPermission(flyPermission)); // 输出: true (因为用户属于admin组)
```

---
</details>
